language: python
python:
  - "2.7"
  - "3.7"

matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx


# command to install dependencies
install:
  - pip install pyinstaller

# command to run tests
script:
  - ./build.cmd
  - ./dist/ddns || test -e "config.json"

git:
  depth: 1

