language: python
python:
  - "2.7"
  - "3.7"

dist: xenial

# os: 
#   - linux
#   - osx


# command to install dependencies
install:
  - pip install pyinstaller

# command to run tests
script:
  - ./build.cmd
  - ./dist/ddns || test -e "config.json"

git:
  depth: 1

